
import militar.rangos.Rango;
import militar.soldados.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame {

    // Modelo para la JList
    DefaultListModel<Rango> modeloSoldados = new DefaultListModel<>();

    public MainFrame() {
        initComponents();

        // Crear soldados
        SoldadoRaso soldado1 = new SoldadoRaso("Juan", "1");
        Teniente teniente1 = new Teniente("Pedro", "2", "Alfa");
        Capitan capitan1 = new Capitan("Luis", "3", 10);
        Coronel coronel1 = new Coronel("Carlos", "4", "Ofensiva");

        // Agregar soldados al modelo
        modeloSoldados.addElement(soldado1);
        modeloSoldados.addElement(teniente1);
        modeloSoldados.addElement(capitan1);
        modeloSoldados.addElement(coronel1);

        // Establecer el modelo en la JList
        listSoldados.setModel(modeloSoldados);

        // Listener para la selección en la JList
        listSoldados.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                Rango soldadoSeleccionado = listSoldados.getSelectedValue();
                mostrarDetallesSoldado(soldadoSeleccionado);
            }
        });

        // Acción para el botón de asignar misión
        btnAsignarMision.addActionListener(e -> asignarMision());

        // Acción para el botón de realizar acción
        btnRealizarAccion.addActionListener(e -> realizarAccion());
    }

    private void mostrarDetallesSoldado(Rango soldado) {
        if (soldado != null) {
            lblNombre.setText("Nombre: " + soldado.getNombre());
            lblID.setText("ID: " + soldado.getId());
            lblRango.setText("Rango: " + soldado.getRango());
    
            // Limpiar información específica
            lblInfoEspecifica.setText("");
    
            // Mostrar información específica según el tipo de soldado
            if (soldado instanceof Capitan) {
                Capitan capitan = (Capitan) soldado;
                lblInfoEspecifica.setText("Soldados bajo mando: " + capitan.getCantidadSoldadosBajoSuMando());
            } else if (soldado instanceof Teniente) {
                Teniente teniente = (Teniente) soldado;
                lblInfoEspecifica.setText("Unidad: " + teniente.getUnidad());
            } else if (soldado instanceof Coronel) {
                Coronel coronel = (Coronel) soldado;
                lblInfoEspecifica.setText("Estrategia: " + coronel.getEstrategia());
            } else {
                lblInfoEspecifica.setText("");
            }
        }
    }

    private void asignarMision() {
        Rango soldadoSeleccionado = listSoldados.getSelectedValue();
        if (soldadoSeleccionado != null) {
            String mision = txtMision.getText();
            if (!mision.isEmpty()) {
                String mensaje = soldadoSeleccionado.asignarMision(mision);
                txtMision.setText("");
                txtAreaAcciones.append(mensaje + "\n");
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese una misión.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un soldado.");
        }
    }

    private void realizarAccion() {
        Rango soldadoSeleccionado = listSoldados.getSelectedValue();
        if (soldadoSeleccionado != null) {
            String accion = soldadoSeleccionado.realizarAccion();
            txtAreaAcciones.append(accion + "\n");
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un soldado.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        scrollPaneList = new javax.swing.JScrollPane();
        listSoldados = new javax.swing.JList<>();
        panelDetalles = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblRango = new javax.swing.JLabel();
        lblInfoEspecifica = new javax.swing.JLabel();
        txtMision = new javax.swing.JTextField();
        btnAsignarMision = new javax.swing.JButton();
        btnRealizarAccion = new javax.swing.JButton();
        scrollPaneTextArea = new javax.swing.JScrollPane();
        txtAreaAcciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Militar");

        splitPane.setDividerLocation(200);

        scrollPaneList.setViewportView(listSoldados);

        splitPane.setLeftComponent(scrollPaneList);

        lblNombre.setText("Nombre:");

        lblID.setText("ID:");

        lblRango.setText("Rango:");

        lblInfoEspecifica.setText("Info Específica:");

        btnAsignarMision.setText("Asignar Misión");

        btnRealizarAccion.setText("Realizar Acción");

        javax.swing.GroupLayout panelDetallesLayout = new javax.swing.GroupLayout(panelDetalles);
        panelDetalles.setLayout(panelDetallesLayout);
        panelDetallesLayout.setHorizontalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblID)
                    .addComponent(lblRango)
                    .addComponent(lblInfoEspecifica)
                    .addComponent(txtMision, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsignarMision)
                    .addComponent(btnRealizarAccion))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelDetallesLayout.setVerticalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRango)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfoEspecifica)
                .addGap(18, 18, 18)
                .addComponent(txtMision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAsignarMision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRealizarAccion)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(panelDetalles);

        txtAreaAcciones.setColumns(20);
        txtAreaAcciones.setRows(5);
        scrollPaneTextArea.setViewportView(txtAreaAcciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
            .addComponent(scrollPaneTextArea)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAsignarMision;
    private javax.swing.JButton btnRealizarAccion;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblInfoEspecifica;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRango;
    private javax.swing.JList<Rango> listSoldados;
    private javax.swing.JPanel panelDetalles;
    private javax.swing.JScrollPane scrollPaneList;
    private javax.swing.JScrollPane scrollPaneTextArea;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTextArea txtAreaAcciones;
    private javax.swing.JTextField txtMision;
    // End of variables declaration
}
